---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    password: AgCfOPmoCYeU2GWS0VUS3KwYLnXIpatSp/ZkDDyh9S6ZBUEZ2Q5HOMUyA47DiGFEYRswtmVRYuNcMBs7dSHyvDbqFOtMEFpBe/M1HlOyDD0KMvSjfR3OEp0BP5Ap6rMp7D4zzEQd7j3eARRUukIzBrgU/JbGFykGEXmitazoyuTQzKOSNgL+g352xv1PvErMsgnRUkZdg9cstx4W9o3fU7dh7MOgQdNEBT8p/1VFYaWIR3aohX+1fpgOvVxTRawq/VjoXi89jESOvZHIezADQyFx/kYZANBd/T2awzRGtjkdZA4/XOpf+UJ9yoV3gPllkR6abLKB7EDCVFoKA4jVzsIccl2nrtFZX8H18s/ndz6whkNIX+hUCPYAesbs1PjdrJV4HuHp266cjGuj/D3uBCIk/7Bli5dw96NwcCSzfuatAzfj8JWsS4HIkaJbRAbgwshpdB6UwI4B+VwDTYJxAm0nyGkNcbDOjjIqXYHIfNg0JWCA/iXmQFPjLCjiL0p97Bese16WVBqaIZJdojAy5h+2R6hIR3RBnN5aRQagPRtw5Xr8F4iB/LD4kQJeuhkXZNmuRj9DMzFChzHc/qrg3nJRo8Mvu0asfULlRDoVKLn29HdqRGtm5MFFjnNv62D1pyk/7Yq7BEJwR1WU4YdaQT5/uB57NYDIWPFx/+hiiPOLR2zoE/iUthc5fuN/fiK1iBwfm85ofS8flQcsMw==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
    type: Opaque
