name: DevSecOps CI/CD

on:
  push:
    branches:
      - main

jobs:
  tfsec:
    name: Terraform Security Scan (tfsec)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan Terraform code with tfsec
        run: |
          TFSEC_VERSION=v1.28.14
          wget https://github.com/aquasecurity/tfsec/releases/download/${TFSEC_VERSION}/tfsec-linux-amd64 -O tfsec
          chmod +x tfsec
          sudo mv tfsec /usr/local/bin/tfsec
          tfsec --soft-fail ./terraform

  trivy:
    name: Docker Image Scan (Trivy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: docker build -t suchitaa/flask-app:latest .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: suchitaa/flask-app:latest
      - name: Push Docker image
        run: docker push suchitaa/flask-app:latest

  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    needs: [tfsec, trivy]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Apply SealedSecrets
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig
        run: kubectl apply -f k8s/sealed-secrets/ --validate=false

      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig
        run: kubectl apply -f k8s/deployments/
